# lsqfitgp/__init__.py
#
# Copyright (c) 2020, 2022, 2023, 2024, 2026, Giacomo Petrillo
#
# This file is part of lsqfitgp.
#
# lsqfitgp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# lsqfitgp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with lsqfitgp.  If not, see <http://www.gnu.org/licenses/>.

"""
Module to fit Gaussian processes.

See the manual at https://gattocrucco.github.io/lsqfitgp/docs
"""

from lsqfitgp._version import __version__  # noqa: F401  # generated by hatch-vcs

# these first because they modify global state
# isort: off
from lsqfitgp import _patch_jax  # noqa: F401
from lsqfitgp import _patch_gvar  # noqa: F401
# isort: on

from lsqfitgp import bayestree, copula  # noqa: F401
from lsqfitgp._array import (  # noqa: F401
    StructuredArray,
    asarray,
    broadcast,
    broadcast_arrays,
    broadcast_to,
    unstructured_to_structured,
)
from lsqfitgp._Deriv import Deriv  # noqa: F401
from lsqfitgp._fastraniter import raniter, sample  # noqa: F401
from lsqfitgp._fit import empbayes_fit  # noqa: F401
from lsqfitgp._GP import GP  # noqa: F401
from lsqfitgp._gvarext import (  # noqa: F401
    fmtspec_kwargs,
    from_jacobian,
    gvar_format,
    gvar_gufunc,
    jacobian,
    switchgvar,
    uformat,
)
from lsqfitgp._Kernel import (  # noqa: F401
    CrossIsotropicKernel,
    CrossKernel,
    CrossStationaryKernel,
    IsotropicKernel,
    Kernel,
    StationaryKernel,
    crossisotropickernel,
    crosskernel,
    crossstationarykernel,
    isotropickernel,
    kernel,
    stationarykernel,
)
from lsqfitgp._kernels import *  # noqa: F403  # safe, _kernels/__init__.py only imports kernels
