# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, windows-latest, macos-latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/tests-requirements.txt
    - name: Test with pytest
      run: make tests
    - name: Save coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-${{ matrix.os }}-py${{ matrix.python-version }}
        path: htmlcov

  postcov:

    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report-ubuntu-latest-py3.10
          path: htmlcov
      - run: |
          pwd
          ls -al
      - name: Copy coverage to github pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: htmlcov
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
