# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/tests-requirements.txt
    - name: Test with pytest
      run: |
        make tests
    - name: Save coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-${{ matrix.os }}-py${{ matrix.python-version }}
        path: htmlcov

  postcov:

    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report-ubuntu-latest-py3.10
      - name: Copy coverage to github pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          # Git domain (default github.com)
          # domain: # optional, default is github.com
          # GitHub repository where assets will be deployed (default $GITHUB_REPOSITORY)
          # repo: # optional
          # Git branch where assets will be deployed
          # target_branch: # optional, default is gh-pages
          # Create incremental commit instead of doing push force
          # keep_history: # optional, default is false
          # Allow an empty commit to be created
          # allow_empty_commit: # optional, default is true
          # Build directory to deploy
          build_dir: htmlcov
          # Whether to treat build_dir as an absolute path
          # absolute_build_dir: # optional, default is false
          # If enabled, the content of symbolic links will be copied
          # follow_symlinks: # optional, default is false
          # The committer name and email address
          # committer: # optional
          # The author name and email address
          # author: # optional
          # Commit message
          # commit_message: # optional
          # Write the given domain name to the CNAME file
          # fqdn: # optional
          # Allow Jekyll to build your site
          jekyll: false # optional, default is true
          # If enabled, nothing will be pushed
          # dry_run: # optional, default is false
          # Enable verbose output
          # verbose: # optional, default is false
